; PlatformIO Project Configuration File

[env:esp32c3-matrix]
platform   = espressif32
board      = seeed_xiao_esp32c3
framework  = arduino
monitor_speed   = 115200
monitor_rts     = 0
monitor_dtr     = 0
monitor_filters = esp32_exception_decoder
build_flags =
    -D FASTLED_RMT_MAX_CHANNELS=1
lib_deps =
    fastled/FastLED @ ^3.6.0
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.3.1
